#!/bin/bash

#set the default value
URL=""

if [ ! -z $1 ]; then
	if [ "$1" == "help" ]  || [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
		printf "Usage: $0 <server url>  Get the docker registry credentials for the given URL from the secretservice docker credential store\n"
		exit 1
	fi
	URL="$1"
fi

secret=$(echo "$URL" | docker-credential-secretservice get | jq .Secret -r 2> /dev/null)
if [ -z $secret ]; then
	echo "no password found"
	exit 1
fi

username=$(echo "$URL" | docker-credential-secretservice get | jq .Username -r 2> /dev/null)
if [ -z $username ]; then
	echo "no password found"
	exit 1
fi

auth="$username:$secret"
echo $auth
