#!/bin/bash

#set the default value
URL=""

if [ ! -z $1 ]; then
	if [ "$1" == "help" ]  || [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
		printf "Usage: $0 <server url>  list the available docker images on the given server"
		exit
	fi
	URL="$1"
fi

auth=$(listDockerCredentials "$URL")
if [ $? -eq 1 ]; then
	echo "Error getting credentials for URL \"$URL\""
	exit 1
fi
curl -u $auth -s -X GET https://"$URL"/v2/_catalog | jq -r ".repositories | .[]"
